quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true

quarkus.security.users.embedded.users.mitarbeiter=mitarbeiter123
quarkus.security.users.embedded.roles.mitarbeiter=mitarbeiter

quarkus.security.users.embedded.users.verwaltung=verwaltung123
quarkus.security.users.embedded.roles.verwaltung=verwaltung

quarkus.security.users.embedded.users.admin=admin123
quarkus.security.users.embedded.roles.admin=verwaltung,admin

quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.login-page=/login/
quarkus.http.auth.form.error-page=/login/?fehler
quarkus.http.auth.form.landing-page=/verwaltung.html
# Verwaltungsseite nur nach Login
quarkus.http.auth.permission.verwaltung.paths=/verwaltung.html
quarkus.http.auth.permission.verwaltung.policy=authenticated
